### ISSUE TITLE
Code Error on running evaluation 

### ISSUE THREAD

**Issue by yhyu13** [SwiftSage/SwiftSage#6]
Following mentioned evaluation in readme, I encountered following error. Let me know if there is a bug in your provided code.

```
$ CUDA_VISIBLE_DEVICES=0 python eval_agent_fast_slow.py     --task_nums "28"     --set "test_mini"     --seed 42     --debug_var "450"     --gpt_version "gpt-4"     --output_path "fast_slow_logs/tmp_gpt4/"
{'jar_path': None, 'task_nums': '28', 'env_step_limit': 300, 'lm_path': 'yuchenlin/swift_sw', 'simplification_str': 'easy', 'beams': 5, 'max_episode_per_file': 9999, 'mode': 'fast_system', 'set': 'test_mini', 'output_path': 'fast_slow_logs/tmp_gpt4/', 'compose_mode': 'v4', 'model_parallelism_size': 1, 'seed': 42, 'max_input_len': 1024, 'cut_off': True, 'sbert': True, 'no_stop': True, 'slow_agent': True, 'gpt_version': 'gpt-4', 'local_llm': 'none', 'demo_file': 'data_utils/demos.json', 'debug_var': 450}
fast_slow_logs/tmp_gpt4/task28.log
Downloading (…)okenizer_config.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.54k/2.54k [00:00<00:00, 429kB/s]
Downloading spiece.model: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 792k/792k [00:01<00:00, 634kB/s]
Downloading (…)/main/tokenizer.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.42M/2.42M [00:01<00:00, 1.58MB/s]
Downloading (…)cial_tokens_map.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.20k/2.20k [00:00<00:00, 1.45MB/s]
Downloading (…)lve/main/config.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 788/788 [00:00<00:00, 152kB/s]
Downloading pytorch_model.bin: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.57G/1.57G [02:17<00:00, 11.4MB/s]
Downloading (…)001fa/.gitattributes: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 690/690 [00:00<00:00, 178kB/s]
Downloading (…)_Pooling/config.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 190/190 [00:00<00:00, 120kB/s]
Downloading (…)3bbb8001fa/README.md: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3.69k/3.69k [00:00<00:00, 2.58MB/s]
Downloading (…)bb8001fa/config.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 629/629 [00:00<00:00, 444kB/s]
Downloading (…)ce_transformers.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 122/122 [00:00<00:00, 93.6kB/s]
Downloading pytorch_model.bin: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 90.9M/90.9M [00:08<00:00, 11.3MB/s]
Downloading (…)nce_bert_config.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 53.0/53.0 [00:00<00:00, 10.3kB/s]
Downloading (…)cial_tokens_map.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 112/112 [00:00<00:00, 110kB/s]
Downloading (…)001fa/tokenizer.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 466k/466k [00:00<00:00, 743kB/s]
Downloading (…)okenizer_config.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 314/314 [00:00<00:00, 301kB/s]
Downloading (…)3bbb8001fa/vocab.txt: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 232k/232k [00:00<00:00, 606kB/s]
Downloading (…)b8001fa/modules.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 229/229 [00:00<00:00, 227kB/s]
Traceback (most recent call last):
  File "eval_agent_fast_slow.py", line 627, in <module>
    main()
  File "eval_agent_fast_slow.py", line 624, in main
    eval(args, int(task_num), logger)
  File "eval_agent_fast_slow.py", line 402, in eval
    used_sys2, return_result = findValidActionWithSystem2(predStrs, env, task_num, task_description, info['look'],
  File "/SwiftSage/eval_utils.py", line 589, in findValidActionWithSystem2
    messages=[{"role": "user", "content": prompt_to_next_actions},
UnboundLocalError: local variable 'prompt_to_next_actions' referenced before assignment

```

**Comment by yuchenlin** [comment]
hmm I couldn't reproduce such an issue.. is it possible that your openai key has an issue; and cause an exception that is not catached?   or maybe a version difference.

i will double check it and catch this exception anyway

**Comment by yhyu13** [comment]
@yuchenlin Wait, does OpenAI key involved at that stage already? I haven't set that evn up at that moment, should I?

**Comment by yuchenlin** [comment]
yeah there are some dependency so we'll need to set up the apis first
